pub enum Val {
    Address(String),
    //BigMap { kty: Box<Ty>, vty: Box<Ty> },
    //Bls12_381_fr,
    //Bls12_381_g1,
    //Bls12_381_g2,
    Bool(bool),
    //Bytes,
    //Chain_id,
    //Contract { ty: Ty },
    Int(i128),
    //Key,
    //Key_hash,
    //Lambda { ty1: Ty, ty2: Ty },
    //List { ty: Type },
    //Map { kty: Ty, vty: Ty },
    Mutez(i128),
    Nat(u128),
    //Never,
    //Operation,
    //Option { ty: Ty },
    //Or{ ty1, ty2},
    //Pair {ty1, ty2},
    //Sapling_state {n},
    //Sapling_transaction {n},
    //Set cty,
    //Signature,
    String(String),
    //Ticket cty,
    //Timepstamp,
    //Unit,
}
